PARTICIPATION_SIGNATURE = [
    "Drei der Besten! Er hat sie bezahlen lassen! Und das vollendet einen wundervollen Hattrick!",
    "Er ist ein harter Brocken, ich denke, er wird weitermachen!" "Prost, Geoff!",
    "Tut mir leid, dass ich dich unterbreche, Alex, aber das könnte eine Chance sein!",
    "Das ist eine Weltklasse-Parade von einem Weltklasse-Torwart.",
    "Hoch. Breit. Und überhaupt nicht hübsch.",
    "Er hat das Preisausschreiben um den Ball gewonnen.",
    "Das nennt der Abiturient antizipieren.",
    "Sogar die Essensversorgung ist hier sehr gut. Buschi, lass mich noch mal in die Bratwurst beißen, sag du mal was.",
    "Fußball ist ein einfaches Spiel: 22 Männer jagen 90 Minuten einem Ball nach und am Ende gewinnen die Deutschen.",
    "Verzogen, wie ein verzogenes Kind. Und wie ein verzogenes Kind steht er dann auch zum Ball, nämlich alles andere als optimal.",
    "Tja, mein Lieber, das sieht aus wie Eckfahnenzielschießen.",
    "Ja, das ist ganz nett anzusehen, denken sich auch die Verteidiger. Fehlt nur noch, dass sie klatschen.",
    "Ich will ja nicht übertreiben, aber der ging kilometerweit am Tor vorbei.",
    "In Afrika würden sie sagen, da liegt ein Voodoozauber über diesem Tor. Sie treffen es einfach nicht.",
    "Wenn alle Angriffe so kurz ablaufen, dann bringst du davon 90 pro Spiel unter!",
    "Ein Pass wie eine Beethoven-Sonate!",
    "Vertan, vertan, sprach der Hahn.",
    "It’s time for a change – Wechselzeit.",
    "Ohh man das sind doch alle Profis, wenn er den nicht reinmacht, nehmt ihn raus, dann macht ihn der Busfahrer rein.",
    "Ein süßes, kleines Zuckerpässchen.",
    "Das sollte eine Bananenflanke werden, sie war aber leider nur Fallobst.",
    "Diese Flanke ging in Richtung von Kareem Abdul-Jabbar. Das war mal ein amerikanischer Basketballer, der war 2,20 Meter groß.",
    "Wo war er denn mit seinen Gedanken? Vielleicht schon in der 3. Halbzeit?",
    "Sie haben aber auch gekämpft, bis die Socken qualmen.",
    "Da springt er…wie ein Springbock",
    "Herr Ober, zwei Kurze bitte.",
    "Manni versteh mich nicht falsch, aber ich bin jetzt in diesen Jungen verliebt",
    "Richtig Rammel-Bammel hier, die sind happy über dieses Tor.",
    "Den hätte meine Oma mit der Mütze gefangen.",
    "Ich glaube , den hätte Manni Breuckmann gemacht.",
    "Ich habe fertig!",
    "Die Flanke! Die Flanke! Die Flanke!",
    "Wer 1:0 führt, hat schon gewonnen.",
    "Der Ball ist rund und ein Spiel dauert 90 Minuten.",
    "Elf Freunde müsst ihr sein.",
    "Fußball ist Krieg ohne Waffen.",
    "Der Schiedsrichter hat immer Recht – auch wenn er mal falsch liegt.",
    "Wenn du den Ball hast, kannst du nicht verlieren.",
    "Wir spielen hier keinen Handball!",
    "Aus dem Augenblick ist ein Augenblick getroffen worden.",
    "Ich wäre ja selbst gern Fußballgott geworden.",
    "Fußball ist wie Schach, nur ohne Würfel.",
    "Gegen Italien gewinnt man nur im Spiel 1‑gegen‑1.",
    "Ich habe keine Ahnung, wie wir gewonnen haben.",
    "Es ist ein Spiel der Leidenschaft.",
    "Ich habe Tore geschossen, die du hier nicht siehst.",
    "Der Trainer ist schuld, egal was passiert.",
    "Wir haben nicht verloren, wir haben nur nicht genug Tore geschossen.",
    "Wenn der Schiri pfeift, ist das Spiel vorbei.",
    "Im Zweifel für den Angreifer!",
    "Das Runde muss ins Eckige!",
    "Ich liebe April, Mai und Juni.",
    "Wir haben alles gegeben – außer vielleicht den Sieg.",
    "Fußball ohne Fans ist wie Pommes ohne Mayo.",
    "Wir haben ein Eigentor gemacht … für den Gegner!",
    "Der beste Spieler auf dem Platz war der Schiedsrichter.",
    "Wir müssen kompakt stehen und aggressiv pressen.",
    "Ich sehe keine Probleme, nur Möglichkeiten.",
    "Wir sind gut funktionierend schlecht.",
    "Ich habe den Ball gesehen … aber nicht getroffen.",
    "Das Spielfeld war zu klein / zu groß / zu windig.",
    "Wir müssen die Intensität erhöhen.",
    "Wenn der Trainer pfeift, macht der Spieler nicht mit.",
    "Wir haben gut verteidigt – mit Ausnahme der Gegentore.",
    "Das ist ein Tackling – kein Schachzug!",
    "Der Gegner spielt sehr tief… im eigenen Sechzehner!",
    "Wir wollten den Sieg – der Sieg wollte nicht!",
    "Mein Schnürsenkel war offen – daher das Tor!",
    "Ich hab‘ den Ball vorher schon gesehen… irgendwie… irgendwann…",
    "Der Trainer ist ein Genie – in kleinen Pausen!",
    "50% Spiel – 50% Zufall – 100% Fußball!",
    "Wir sind Fußballer, keine Physiker!",
    "Wir wollten Risiko – bekamen Risiko plus!",
    "Das war ein klassisches 0:0!",
    "Wenn wir gewinnen, schreibe ich ein Buch.",
    "Der Trainer hat mir gesagt, ich soll laufen… also laufe ich!",
    "Wir haben die letzte Chance vergeben… und die nächste auch.",
    "Heute ist ein guter Tag zum Verlieren.",
    "Das Runde rollt – der Rest ist Geschichte.",
    "Fußball ist wie eine Beziehung – kompliziert!",
    "Ein Tor in letzter Minute? Klar, warum nicht!",
    "Lieber spät als gar kein Tor!",
    "Das war ein Eigentor… aus Überzeugung!",
    "Wenn der Ball eckig wäre, hätten wir bessere Chancen!",
    "Ich hab‘ ein Gefühl – aber keinen Plan.",
    "Wir brauchen ein Tor – oder zwei… mindestens drei!",
    "Ich hab‘ keine Erklärungen… nur Ausreden!",
    "Wir verteidigen gut – außer vor dem Tor!",
    "Die Latte war näher am Ball als wir.",
    "Die Tabelle lügt – meistens!",
    "Ich traue dem Ergebnis nicht – und dem Schiedsrichter auch nicht!",
    "I‘ve failed over and over and over again in my life. And that is why I succeed.",
    "Hard work beats talent when talent fails to work hard.",
    "Concentration and mental toughness are the margins of victory.",
    "Defense is a choice, not a chore.",
    "My belief is stronger than your doubt.",
    "Play the right way. Play unselfishly... always be willing to sacrifice for the team.",
    "Average players want to be left alone. Good players want to be coached. Great players want to be told the truth.",
    "Being close ain’t good enough.",
    "Im not a role model… Just because I dunk a basketball doesn’t mean I should raise your kids.",
    "I always keep a ball in the car. You never know.",
    "Some people want it to happen, some wish it would happen, others make it happen.",
    "Good, better, best… Never let it rest. Until your good is better and your better is best.",
    "Talent wins games, but teamwork and intelligence win championships.",
    "The strength of the team is each individual member.",
    "The harder the battle, the sweeter the victory.",
    "Ive missed more than 9000 shots... and that is why I succeed.",
    "Don’t be afraid of failure. This is the way to succeed.",
    "Success is not about the destination, but about the journey.",
    "Excellence is not a singular act, but a habit.",
    "Success is not an accident... success is actually a choice.",
    "I play every game like it’s my last.",
    "Ball don’t lie!",
    "We don’t feel pressure, the pressure is on them.",
    "I’m Kevin Durant. Y’all know who I am.",
    "Everybody acting tough when theyre up.",
    "I’m a fun guy.",
    "Mamba out!",
    "Not 1, not 2, not 3...",
    "I dont give a sh*t.",
    "Who’s coming in second?",
    "I’ll beat yo ass!",
    "Cut the check.",
    "Bang!",
    "Shazam!",
    "Whammo Time!",
    "Oh Me, Oh My!",
    "Swish-a-roo for Two!",
    "Fasten your seat belts, gang…",
    "Put This One in the Ol Deep Freeze",
    "Ive got a theory… give 100% all of the time.",
    "Defense wins championships.",
    "Teamwork makes the dream work.",
    "Hard work beats hardship.",
    "It’s not about what you have… it’s about what you make of it.",
    "I really get motivated when I have doubters.",
    "Failure doesn’t exist.",
    "Basketball isn’t just a sport, it is an art.",
    "When you are not practicing, someone else is getting better.",
    "I can accept failure… but I can’t accept not trying.",
    "Football is like life – it requires perseverance, self‑denial, hard work, sacrifice, dedication and respect for authority.",
    "The only place success comes before work is in the dictionary.",
    "Winning isn’t everything, it’s the only thing.",
    "Winning isn’t everything, but wanting to win is.",
    "You fail all the time. That’s how you succeed.",
    "Don’t expect to win every game, but always go into every game expecting to win.",
    "The difference between ordinary and extraordinary is that little extra.",
    "Teamwork is what makes common people capable of uncommon results.",
    "If you aren’t going all the way, why go at all?",
    "Adversity makes you stronger – always has and always will.",
    "You play to win the game.",
    "Pressure? I welcome it.",
    "I’m always looking for ways to improve.",
    "When you win, nothing hurts.",
    "If you want to win, do the ordinary things better than anyone else does them day in and day out.",
    "Nobody who ever gave his best regretted it.",
    "Success demands singleness of purpose.",
    "Stay focused. Your start does not determine how you’re going to finish.",
    "You are never a loser until you quit trying.",
    "If you dont want to be the best, then theres no reason going out and trying to accomplish anything.",
    "Today I will do what others dont, so tomorrow I can accomplish what others cant.",
    "The spirit, the will to win, and the will to excel are the things that endure.",
    "Pressure is something you feel when you dont know what the hell youre doing.",
    "Football is a team game. So is life.",
    "The best defense is a good offense.",
    "Defense wins championships.",
    "Nobody in football should be called a genius.",
    "Luck is what happens when preparation meets opportunity.",
    "Football is like war - it’s quiet in the rear but hell in the front.",
    "Champions keep playing until they get it right.",
    "You can learn a line from a win and a book from a defeat.",
    "The most valuable player is the one who makes the most players valuable.",
    "Ability is what you’re capable of doing - motivation determines what you do.",
    "Goals determine what you’re going to be.",
    "Hard work beats talent when talent doesn’t work hard.",
    "Preparation beats perspiration.",
    "Sweat more in practice, bleed less in battle.",
    "Individual commitment to a group effort – that is what makes a team work.",
    "It’s not whether you get knocked down - it’s whether you get up.",
    "Perfection is not attainable, but if we chase perfection we can catch excellence.",
    "The will to win is not nearly so important as the will to prepare to win.",
    "All I can do is all I can do, and all I can do is enough.",
    "Don’t count the days - make the days count.",
    "In football, you make your own luck.",
    "It’s not the size of the dog in the fight, it’s the size of the fight in the dog.",
    "You have to expect things of yourself before you can do them.",
    "The more difficult the victory, the greater the happiness in winning.",
    "Success is where preparation and opportunity meet.",
    "When you’re good at something you’ll tell everyone. When you’re great at something, they will tell you.",
    "Je moet altijd zorgen dat je één doelpunt meer scoort als de tegenstander."
]